image:
  - Visual Studio 2017 Preview

environment:
  BOOST_ROOT: C:/Libraries/boost_1_67_0
  matrix:
    - platform: x86
      GENERATOR: "Visual Studio 15 2017"
      BOOST_LIBRARYDIR: "%BOOST_ROOT%/lib32-msvc-14.1"
    - platform: x64
      GENERATOR: "Visual Studio 15 2017 Win64"
      BOOST_LIBRARYDIR: "%BOOST_ROOT%/lib64-msvc-14.1"

configuration:
  - Debug
  - Release

before_build:
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%

    cd ..

    git clone https://github.com/rhalbersma/xstd.git

    git clone https://github.com/rhalbersma/int_set.git
      
    cd %APPVEYOR_BUILD_FOLDER%

    mkdir build         
    
    cd build       
    
    cmake .. -G "%generator%"   

build_script:
- cmake --build .

test_script:
- ctest -E "search|traversal"
