image:
  - Visual Studio 2017
 
environment:
    generator: "Visual Studio 15 2017 Win64"
    BOOST_ROOT: C:/Libraries/boost_1_66_0
    BOOST_LIBRARYDIR: C:/Libraries/boost_1_66_0/lib64-msvc-14.1
    PATH: "%BOOST_LIBRARYDIR%;%PATH%"
    
configuration:
  - Debug
    
before_build:
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%

    cd ..

    git clone https://github.com/rhalbersma/xstd.git

    git clone https://github.com/rhalbersma/int_set.git
    
    mkdir ext

    cd ext

    git clone https://github.com/rhalbersma/hash_append.git

    cd ..
    
    cd %APPVEYOR_BUILD_FOLDER%
    
    mkdir build         
    
    cd build       
    
    cmake .. -G "%generator%"   

build_script:
- cmd: >-
    cmake --build .
    
test_script:
- cmd: >-
    ctest
