language: cpp
os: linux
dist: trusty
sudo: false

matrix:
  include:
    - env: CXX_COMPILER=clang++-6.0 CXX=g++-8
      addons: { apt: { packages: ["clang-6.0", "g++-8"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-trusty-6.0"] } }

    - env: CXX_COMPILER=clang++-7 CXX=g++-8
      addons: { apt: { packages: ["clang-7", "g++-8"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-trusty"] } }

    - env: CXX_COMPILER=g++-8
      addons: { apt: { packages: ["g++-8"], sources: ["ubuntu-toolchain-r-test"] } }

install:

################################################################################
# All manual dependencies are installed in ${TRAVIS_BUILD_DIR}/../deps
################################################################################
- |
  DEPS_DIR="${TRAVIS_BUILD_DIR}/../deps"
  mkdir -p ${DEPS_DIR}
  
################################################################################
# Install the latest Boost and build Boost.Test (compiled with g++-8)
################################################################################
- |
  BOOST_VERSION=1.66.0
  BOOST_DIR=${DEPS_DIR}/boost-${BOOST_VERSION}
  BOOST_URL="https://dl.bintray.com/boostorg/release/${BOOST_VERSION}/source/boost_${BOOST_VERSION//\./_}.tar.bz2"
  mkdir -p ${BOOST_DIR} && travis_retry wget --quiet -O - ${BOOST_URL} | tar --strip-components=1 -xj -C ${BOOST_DIR}
  cd ${BOOST_DIR} && ./bootstrap.sh --with-libraries=program_options,test && ./b2 -d0

################################################################################
# Install the latest CMake
################################################################################
- |
  CMAKE_VERSION=3.11.1
  CMAKE_DIR=${DEPS_DIR}/cmake-${CMAKE_VERSION}
  CMAKE_URL="http://www.cmake.org/files/v${CMAKE_VERSION%.[0-9]}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
  mkdir -p ${CMAKE_DIR} && travis_retry wget --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${CMAKE_DIR}
  export PATH=${CMAKE_DIR}/bin:${PATH}

################################################################################
# Install the dependent GitHub repositories xstd and hash_append
################################################################################
- |
  cd ${DEPS_DIR}/..
  git clone https://github.com/rhalbersma/xstd.git
  git clone https://github.com/rhalbersma/int_set.git
  mkdir -p ext && cd ext
  git clone https://github.com/rhalbersma/hash_append.git
  cd ..

before_script:
- |
  cd ${TRAVIS_BUILD_DIR}
  mkdir build && cd build
  cmake .. -DCMAKE_CXX_COMPILER=${CXX_COMPILER} -DBOOST_ROOT="${BOOST_DIR}" -DBOOST_LIBRARYDIR="${BOOST_DIR}/stage/lib"
 
script: 
- |
  cmake --build .
  ctest -E "search|traversal"

after_success:
- |
  if [[ "${CXX_COMPILER}" == "g++-8" ]]; then
    bash <(curl -s https://codecov.io/bash)
  fi

notifications:
  email: false
