language: cpp
os: linux
dist: trusty
sudo: false

matrix:
  include:
    - env: CXX_COMPILER=clang++-6.0 CXX=g++-8
      addons: { apt: { packages: ["clang-6.0", "g++-8"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-trusty-6.0"] } }

    - env: CXX_COMPILER=clang++-7 CXX=g++-8
      addons: { apt: { packages: ["clang-7", "g++-8"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-trusty"] } }

    - env: CXX_COMPILER=g++-8
      addons: { apt: { packages: ["g++-8"], sources: ["ubuntu-toolchain-r-test"] } }

install:
- |
  sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 90
  sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
  
################################################################################
# All manual dependencies are installed in ${TRAVIS_BUILD_DIR}/../deps
################################################################################
- |
  DEPS_DIR="${TRAVIS_BUILD_DIR}/../deps"
  mkdir -p ${DEPS_DIR}
  
################################################################################
# Install the latest Boost and build Boost.Test (compiled with g++-8)
################################################################################
- |
  cd ${DEPS_DIR}
  BOOST_URL="https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.tar.bz2"
  mkdir -p boost-1.66.0 && travis_retry wget --quiet -O - ${BOOST_URL} | tar --strip-components=1 -xj -C boost-1.66.0
  cd boost-1.66.0 
  ./bootstrap.sh --with-toolset=gcc --with-libraries=test,program_options && sudo ./b2 -d0 install
  sudo ldconfig /usr/local/lib

################################################################################
# Install the dependent GitHub repositories xstd and hash_append
################################################################################
- |
  cd ${DEPS_DIR}/..
  git clone https://github.com/rhalbersma/xstd.git
  mkdir -p ext && cd ext
  git clone https://github.com/rhalbersma/hash_append.git
  cd ..

before_script:
- |
  cd ${TRAVIS_BUILD_DIR}
  mkdir build && cd build
  cmake .. -DCMAKE_CXX_COMPILER=${CXX_COMPILER}
 
script: 
- |
  cmake --build .
  ctest -E "search|traversal"

after_success:
- |
  lcov --capture --directory .. --output-file coverage.info
  bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
